services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
      - PGPORT=5434
    restart: always
    ports:
      - "5434:5434"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
