services:
  catalogdb:
    image: postgres
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

volumes:
  postgres_catalog:


